-- PicoPawn - Ascension community scales
-- AUTO-GENERATED by tools/generate_ascension_scales.py -- do not edit by hand.
-- Add or edit scales in scales/*.json and re-run the generator.
--
-- These are community-submitted stat weights for WoW Ascension, grouped by
-- realm/class/role. Enabled scales show upgrade arrows and percentages on item
-- tooltips. On class-based realms the scales matching your class auto-enable;
-- on classless realms, enable the ones you want from the PicoPawn window.
------------------------------------------------------------

local ScaleProviderName = "Ascension"

function PawnAscensionScaleProvider_AddScales()

	-- Beast Mastery (Hunter, DPS (Ranged)) submitted for Bronzebeard by PicoPawn (starter example)
	PawnAddPluginScale(
		ScaleProviderName,
		"BronzebeardHunterDpsRangedBeastMastery",
		"[Bronzebeard] Hunter - DPS (Ranged): Beast Mastery",
		"abd473",
		{
			["Agility"] = 100, ["Ap"] = 53, ["ArmorPenetration"] = 44, ["CritRating"] = 64, ["HasteRating"] = 45, ["HitRating"] = 61, ["Intellect"] = 1, ["IsWand"] = -1000000, ["Stamina"] = 0.1
		},
		1
	)

	-- Arms (Warrior, DPS (Melee)) submitted for Bronzebeard by PicoPawn (starter example)
	PawnAddPluginScale(
		ScaleProviderName,
		"BronzebeardWarriorDpsMeleeArms",
		"[Bronzebeard] Warrior - DPS (Melee): Arms",
		"c79c6e",
		{
			["Agility"] = 65, ["Ap"] = 45, ["Armor"] = 1, ["ArmorPenetration"] = 65, ["CritRating"] = 80, ["ExpertiseRating"] = 85, ["HasteRating"] = 50, ["HitRating"] = 90, ["IsWand"] = -1000000, ["Stamina"] = 0.1, ["Strength"] = 100
		},
		1
	)

	-- Holy Heal (Priest, Healer) submitted for Voljin by PicoPawn (starter example)
	PawnAddPluginScale(
		ScaleProviderName,
		"VoljinPriestHealerHolyHeal",
		"[Voljin] Priest - Healer: Holy Heal",
		"ffffff",
		{
			["CritRating"] = 45, ["HasteRating"] = 60, ["Intellect"] = 70, ["Mp5"] = 40, ["SpellPower"] = 100, ["Spirit"] = 88, ["Stamina"] = 0.1
		},
		1
	)

	------------------------------------------------------------
	-- Auto-enable scales whose class matches the player, once per character.
	if not PicoPawnAscensionScaleProviderOptions then PicoPawnAscensionScaleProviderOptions = { } end
	if not PicoPawnAscensionScaleProviderOptions.LastAdded then PicoPawnAscensionScaleProviderOptions.LastAdded = 0 end
	local _, Class = UnitClass("player")
	if PicoPawnAscensionScaleProviderOptions.LastAdded < 1 then
		local AutoEnable = {
			{ "BronzebeardHunterDpsRangedBeastMastery", "HUNTER" },
			{ "BronzebeardWarriorDpsMeleeArms", "WARRIOR" },
			{ "VoljinPriestHealerHolyHeal", "PRIEST" },
		}
		local i, Entry
		for i, Entry in ipairs(AutoEnable) do
			if Entry[2] == Class then
				PawnSetScaleVisible(PawnGetProviderScaleName(ScaleProviderName, Entry[1]), true)
			end
		end
	end
	PicoPawnAscensionScaleProviderOptions.LastAdded = 1

	-- Free the function after it runs to save memory.
	PawnAscensionScaleProvider_AddScales = nil

end -- PawnAscensionScaleProvider_AddScales

------------------------------------------------------------

PawnAddPluginScaleProvider(ScaleProviderName, "Ascension community scales", PawnAscensionScaleProvider_AddScales)
