#!/usr/bin/env python3
"""Generate PicoPawn/AscensionScales.lua from the JSON scales in scales/.

Each accepted community scale lives in scales/*.json with this shape:

    {
      "name":    "Hunter BM",              # short display name (required)
      "class":   "Hunter",                 # class name (required)
      "role":    "DPS (Ranged)",           # role/spec (required)
      "server":  "Bronzebeard",            # realm/server, free text (required)
      "version": "3.3.5a",                 # client/addon version (required)
      "author":  "SomePlayer",             # credit (optional)
      "notes":   "...",                    # optional
      "tag":     "( Pawn: v1: \"Hunter BM\": Agility=100, CritRating=64, ... GemQualityLevel=4 )"
    }

The Pawn scale "tag" is what a player gets from PicoPawn in-game (Scales tab ->
copy the export string, or /picopawn backup). This script parses the tag's
stat=value pairs and emits a Pawn plugin scale provider named "Ascension" that
registers every scale, colours it by class, and auto-enables scales whose class
matches the player's class (so the upgrade arrows show up automatically on
class-based realms; on classless realms the player just enables what they want).

Usage:
    python tools/generate_ascension_scales.py

Run this whenever you add or edit a file in scales/, then commit the regenerated
PicoPawn/AscensionScales.lua.
"""

import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCALES_DIR = os.path.join(REPO, "scales")
OUT_LUA = os.path.join(REPO, "PicoPawn", "AscensionScales.lua")

# Standard WotLK class colours (hex, no |cff prefix). Ascension custom classes
# fall back to DEFAULT_COLOR.
CLASS_COLORS = {
    "WARRIOR": "c79c6e", "PALADIN": "f58cba", "HUNTER": "abd473",
    "ROGUE": "fff569", "PRIEST": "ffffff", "DEATHKNIGHT": "c41f3b",
    "SHAMAN": "0070de", "MAGE": "69ccf0", "WARLOCK": "9482c9", "DRUID": "ff7d0a",
}
DEFAULT_COLOR = "1eff00"

# Map a human class name to the UnitClass() token used for auto-enable.
CLASS_TOKENS = {
    "warrior": "WARRIOR", "paladin": "PALADIN", "hunter": "HUNTER",
    "rogue": "ROGUE", "priest": "PRIEST", "death knight": "DEATHKNIGHT",
    "deathknight": "DEATHKNIGHT", "shaman": "SHAMAN", "mage": "MAGE",
    "warlock": "WARLOCK", "druid": "DRUID",
}

TAG_RE = re.compile(r'^\s*\(\s*Pawn\s*:\s*v(\d+)\s*:\s*"([^"]+)"\s*:\s*(.+?)\s*\)\s*$', re.S)
PAIR_RE = re.compile(r'^\s*([A-Za-z0-9]+)\s*=\s*(-?[0-9.]+)\s*$')

# Keys that live in a Pawn tag but are scale *properties*, not item stat weights,
# so they must not go into the plugin scale's Values table.
NON_STAT_KEYS = {"GemQualityLevel", "MetaGemQualityLevel"}


def parse_tag(tag):
    """Return (scale_name, {stat: value}) from a Pawn scale tag, or raise ValueError."""
    m = TAG_RE.match(tag)
    if not m:
        raise ValueError("tag does not match the Pawn scale format")
    _version, name, values_str = m.group(1), m.group(2), m.group(3)
    values = {}
    for pair in values_str.split(","):
        if not pair.strip():
            continue
        pm = PAIR_RE.match(pair)
        if not pm:
            raise ValueError("could not parse stat pair: %r" % pair)
        if pm.group(1) in NON_STAT_KEYS:
            continue
        values[pm.group(1)] = float(pm.group(2))
    if not values:
        raise ValueError("tag has no stat values")
    return name, values


def lua_number(v):
    """Format a number the way the Lua files do (drop trailing .0)."""
    if v == int(v):
        return str(int(v))
    return repr(v)


def slug(*parts):
    s = "_".join(str(p) for p in parts)
    s = re.sub(r"[^A-Za-z0-9]+", "", s.title().replace(" ", ""))
    return s


def load_scales():
    scales = []
    if not os.path.isdir(SCALES_DIR):
        return scales
    paths = []
    for root, _dirs, files in os.walk(SCALES_DIR):
        for fn in files:
            if fn.endswith(".json"):
                paths.append(os.path.join(root, fn))
    for path in sorted(paths):
        fn = os.path.relpath(path, SCALES_DIR)
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        for field in ("name", "class", "role", "server", "version", "tag"):
            if not data.get(field):
                raise SystemExit("%s: missing required field '%s'" % (fn, field))
        try:
            _tagname, values = parse_tag(data["tag"])
        except ValueError as e:
            raise SystemExit("%s: bad tag: %s" % (fn, e))
        data["_values"] = values
        data["_file"] = fn
        scales.append(data)
    return scales


def build_lua(scales):
    lines = []
    w = lines.append
    w("﻿-- PicoPawn - Ascension community scales")
    w("-- AUTO-GENERATED by tools/generate_ascension_scales.py -- do not edit by hand.")
    w("-- Add or edit scales in scales/*.json and re-run the generator.")
    w("--")
    w("-- These are community-submitted stat weights for WoW Ascension, grouped by")
    w("-- realm/class/role. Enabled scales show upgrade arrows and percentages on item")
    w("-- tooltips. On class-based realms the scales matching your class auto-enable;")
    w("-- on classless realms, enable the ones you want from the PicoPawn window.")
    w("------------------------------------------------------------")
    w("")
    w('local ScaleProviderName = "Ascension"')
    w("")
    w("function PawnAscensionScaleProvider_AddScales()")
    w("")

    # Track class token per internal scale name for auto-enable.
    autoenable = []  # (internal_name, class_token)

    seen = set()
    for s in scales:
        internal = slug(s["server"], s["class"], s["role"], s["name"])
        base = internal
        i = 2
        while internal in seen:
            internal = "%s%d" % (base, i)
            i += 1
        seen.add(internal)
        s["_internal"] = internal

        token = CLASS_TOKENS.get(str(s["class"]).strip().lower())
        color = CLASS_COLORS.get(token, DEFAULT_COLOR) if token else DEFAULT_COLOR
        if token:
            autoenable.append((internal, token))

        # Display name: [Server] Class - Role, plus ": Name" only when the name
        # adds information beyond the class/role (avoids "Venomancer - Tank: Venomancer Tank").
        name = str(s["name"]).strip()
        redundant = {
            str(s["role"]).strip().lower(),
            ("%s %s" % (s["class"], s["role"])).strip().lower(),
            str(s["class"]).strip().lower(),
        }
        display = "[%s] %s - %s" % (s["server"], s["class"], s["role"])
        if name.lower() not in redundant:
            display += ": " + name
        display = display.replace('"', "'")

        stat_items = ", ".join(
            '["%s"] = %s' % (stat, lua_number(val))
            for stat, val in sorted(s["_values"].items())
        )

        w("\t-- %s (%s, %s) submitted for %s%s" % (
            s["name"], s["class"], s["role"], s["server"],
            (" by " + str(s["author"])) if s.get("author") else "",
        ))
        w("\tPawnAddPluginScale(")
        w("\t\tScaleProviderName,")
        w('\t\t"%s",' % internal)
        w('\t\t"%s",' % display)
        w('\t\t"%s",' % color)
        w("\t\t{")
        w("\t\t\t%s" % stat_items)
        w("\t\t},")
        w("\t\t1")
        w("\t)")
        w("")

    # Auto-enable matching-class scales once per character.
    w("\t------------------------------------------------------------")
    w("\t-- Auto-enable scales whose class matches the player, once per character.")
    w("\tif not PicoPawnAscensionScaleProviderOptions then PicoPawnAscensionScaleProviderOptions = { } end")
    w("\tif not PicoPawnAscensionScaleProviderOptions.LastAdded then PicoPawnAscensionScaleProviderOptions.LastAdded = 0 end")
    w('\tlocal _, Class = UnitClass("player")')
    w("\tif PicoPawnAscensionScaleProviderOptions.LastAdded < 1 then")
    if autoenable:
        w("\t\tlocal AutoEnable = {")
        for internal, token in autoenable:
            w('\t\t\t{ "%s", "%s" },' % (internal, token))
        w("\t\t}")
        w("\t\tlocal i, Entry")
        w("\t\tfor i, Entry in ipairs(AutoEnable) do")
        w("\t\t\tif Entry[2] == Class then")
        w("\t\t\t\tPawnSetScaleVisible(PawnGetProviderScaleName(ScaleProviderName, Entry[1]), true)")
        w("\t\t\tend")
        w("\t\tend")
    else:
        w("\t\t-- (no scales with a standard class token yet)")
    w("\tend")
    w("\tPicoPawnAscensionScaleProviderOptions.LastAdded = 1")
    w("")
    w("\t-- Free the function after it runs to save memory.")
    w("\tPawnAscensionScaleProvider_AddScales = nil")
    w("")
    w("end -- PawnAscensionScaleProvider_AddScales")
    w("")
    w("------------------------------------------------------------")
    w("")
    w('PawnAddPluginScaleProvider(ScaleProviderName, "Ascension community scales", PawnAscensionScaleProvider_AddScales)')
    w("")
    # CRLF line endings for the WoW client.
    return "\r\n".join(lines)


def main():
    scales = load_scales()
    lua = build_lua(scales)
    with open(OUT_LUA, "w", encoding="utf-8", newline="") as f:
        f.write(lua)
    print("Wrote %s (%d scale%s)" % (
        os.path.relpath(OUT_LUA, REPO), len(scales), "" if len(scales) == 1 else "s"))


if __name__ == "__main__":
    main()
